const landingSO = {
  winter2020: {
    highShoreTemp: 41.5,
    highShoreTempDelta: 2.2,
    highShoreTempN: "4 sites",
    lowShoreTemp: 34.8,
    lowShoreTempDelta: 1.3,
    lowShoreTempN: "3 sites",
    chla: 12.25,
    chlaDelta: 6.20,
    chlaN: "4 sites",
    om: 5.98,
    omDelta: 1.85,
    omN: "4 sites",
    waveMax: 400.93,
    waveMin: 4.61,
    waveN: "4 sites",
    mobileMax: 23,
    mobileMin: 22,
    mobileN: "2 sites",
    sessileMax: 19,
    sessileMin: 16,
    sessileN: "2 sites"
  },
  summer2021: {
    highShoreTemp: 48.2,
    highShoreTempDelta: 1.8,
    highShoreTempN: "3 sites",
    lowShoreTemp: 42.6,
    lowShoreTempDelta: 1.4,
    lowShoreTempN: "3 sites",
    chla: 14.76,
    chlaDelta: 6.43,
    chlaN: "3 sites",
    om: 8.91,
    omDelta: 2.95,
    omN: "3 sites",
    waveMax: 400.93,
    waveMin: 4.61,
    waveN: "4 sites",
    mobileMax: "NA",
    mobileMin: "NA",
    mobileN: "NA",
    sessileMax: "NA",
    sessileMin: "NA",
    sessileN: "NA"
  }
};

export default landingSO;
