const landingNW = {
  winter2020: {
    highShoreTemp: 45.9,
    highShoreTempDelta: 1.8,
    highShoreTempN: "4 sites",
    lowShoreTemp: 34.2,
    lowShoreTempDelta: 7.4,
    lowShoreTempN: "4 sites",
    chla: 24.72,
    chlaDelta: 12.25,
    chlaN: "4 sites",
    om: 8.40,
    omDelta: 3.96,
    omN: "4 sites",
    waveMax: 328.5,
    waveMin: 42.41,
    waveN: "4 sites",
    mobileMax: 24,
    mobileMin: 21,
    mobileN: "4 sites",
    sessileMax: 23,
    sessileMin: 16,
    sessileN: "4 sites"
  },
  summer2021: {
    highShoreTemp: 54.3,
    highShoreTempDelta: 1.7,
    highShoreTempN: "4 sites",
    lowShoreTemp: 51.2,
    lowShoreTempDelta: 2.9,
    lowShoreTempN: "4 sites",
    chla: 20.09,
    chlaDelta: 6.65,
    chlaN: "4 sites",
    om: 8.42,
    omDelta: 4.66,
    omN: "4 sites",
    waveMax: 328.5,
    waveMin: 42.41,
    waveN: "4 sites",
    mobileMax: 38,
    mobileMin: 24,
    mobileN: "4 sites",
    sessileMax: 31,
    sessileMin: 24,
    sessileN: "4 sites"
  }
};

export default landingNW;
