const landingEA = {
  winter2020: {
    highShoreTemp: 44.5,
    highShoreTempDelta: 2.2,
    highShoreTempN: "4 sites",
    lowShoreTemp: 36.5,
    lowShoreTempDelta: 8.1,
    lowShoreTempN: "4 sites",
    chla: 6.91,
    chlaDelta: 4.27,
    chlaN: "4 sites",
    om: 5.66,
    omDelta: 3.40,
    omN: "4 sites",
    waveMax: 610.56,
    waveMin: 10.98,
    waveN: "4 sites",
    mobileMax: 26,
    mobileMin: 17,
    mobileN: "4 sites",
    sessileMax: 26,
    sessileMin: 20,
    sessileN: "4 sites"
  },
  summer2021: {
    highShoreTemp: 56.1,
    highShoreTempDelta: 2.4,
    highShoreTempN: "4 sites",
    lowShoreTemp: 52.5,
    lowShoreTempDelta: 4.5,
    lowShoreTempN: "4 sites",
    chla: 9.69,
    chlaDelta: 4.31,
    chlaN: "4 sites",
    om: 7.53,
    omDelta: 4.56,
    omN: "4 sites",
    waveMax: 610.56,
    waveMin: 10.98,
    waveN: "4 sites",
    mobileMax: 40,
    mobileMin: 30,
    mobileN: "4 sites",
    sessileMax: 33,
    sessileMin: 21,
    sessileN: "4 sites"
  }
};

export default landingEA;
