const landingNE = {
  winter2020: {
    highShoreTemp: 38.9,
    highShoreTempDelta: 8.3,
    highShoreTempN: "4 sites",
    lowShoreTemp: 34.5,
    lowShoreTempDelta: 8.0,
    lowShoreTempN: "4 sites",
    chla: 9.41,
    chlaDelta: 0.78,
    chlaN: "4 sites",
    om: 8.44,
    omDelta: 1.37,
    omN: "4 sites",
    waveMax: 49.59,
    waveMin: 15.05,
    waveN: "4 sites",
    mobileMax: 35,
    mobileMin: 35,
    mobileN: "1 site",
    sessileMax: 18,
    sessileMin: 18,
    sessileN: "1 site"
  },
  summer2021: {
    highShoreTemp: 54.3,
    highShoreTempDelta: 1.4,
    highShoreTempN: "2 sites",
    lowShoreTemp: 51.6,
    lowShoreTempDelta: 0.4,
    lowShoreTempN: "2 sites",
    chla: "NA",
    chlaDelta: "NA",
    chlaN: "NA",
    om: "NA",
    omDelta: "NA",
    omN: "NA",
    waveMax: 49.59,
    waveMin: 15.05,
    waveN: "4 sites",
    mobileMax: "NA",
    mobileMin: "NA",
    mobileN: "NA",
    sessileMax: "NA",
    sessileMin: "NA",
    sessileN: "NA"
  }
};

export default landingNE;
