const landingNE = {
  winter2020: {
    highShoreTemp: 36.5,
    highShoreTempDelta: 6.5,
    highShoreTempN: "4 sites",
    lowShoreTemp: 32.3,
    lowShoreTempDelta: 6.6,
    lowShoreTempN: "4 sites",
    chla: 9.41,
    chlaDelta: 0.78,
    chlaN: "4 sites",
    om: 8.44,
    omDelta: 1.37,
    omN: "4 sites",
    waveMax: 49.59,
    waveMin: 15.05,
    waveN: "4 sites",
    mobileMax: 25,
    mobileMin: 14,
    mobileN: "1 site",
    sessileMax: 23,
    sessileMin: 12,
    sessileN: "1 site"
  },
  summer2021: {
    highShoreTemp: 55.3,
    highShoreTempDelta: "NA",
    highShoreTempN: "1 site",
    lowShoreTemp: 51.3,
    lowShoreTempDelta: "NA",
    lowShoreTempN: "1 site",
    chla: "NA",
    chlaDelta: "NA",
    chlaN: "NA",
    om: "NA",
    omDelta: "NA",
    omN: "NA",
    waveMax: 49.59,
    waveMin: 15.05,
    waveN: "4 sites",
    mobileMax: "NA",
    mobileMin: "NA",
    mobileN: "NA",
    sessileMax: "NA",
    sessileMin: "NA",
    sessileN: "NA"
  }
};

export default landingNE;
