const landingSW = {
  winter2020: {
    highShoreTemp: 45.3,
    highShoreTempDelta: 5.7,
    highShoreTempN: "4 sites",
    lowShoreTemp: 38.9,
    lowShoreTempDelta: 7.8,
    lowShoreTempN: "4 sites",
    chla: 6.56,
    chlaDelta: 2.86,
    chlaN: "4 sites",
    om: 5.66,
    omDelta: 2.04,
    omN: "4 sites",
    waveMax: 462.86,
    waveMin: 59.25,
    waveN: "4 sites",
    mobileMax: 27,
    mobileMin: 20,
    mobileN: "4 sites",
    sessileMax: 21,
    sessileMin: 19,
    sessileN: "4 sites"
  },
  summer2021: {
    highShoreTemp: 54.3,
    highShoreTempDelta: 6.5,
    highShoreTempN: "4 sites",
    lowShoreTemp: 49.4,
    lowShoreTempDelta: 6.2,
    lowShoreTempN: "4 sites",
    chla: 7.23,
    chlaDelta: 2.18,
    chlaN: "4 sites",
    om: 5.65,
    omDelta: 1.86,
    omN: "4 sites",
    waveMax: 462.86,
    waveMin: 59.25,
    waveN: "4 sites",
    mobileMax: 36,
    mobileMin: 31,
    mobileN: "4 sites",
    sessileMax: 40,
    sessileMin: 22,
    sessileN: "4 sites"
  }
};

export default landingSW;
