const landingSO = {
  winter2020: {
    highShoreTemp: 41.8,
    highShoreTempDelta: 2.2,
    highShoreTempN: "4 sites",
    lowShoreTemp: 34.8,
    lowShoreTempDelta: 1.3,
    lowShoreTempN: "3 sites",
    chla: 12.25,
    chlaDelta: 6.20,
    chlaN: "4 sites",
    om: 5.98,
    omDelta: 1.85,
    omN: "4 sites",
    waveMax: 615.54,
    waveMin: 29.62,
    waveN: "4 sites",
    mobileMax: 29,
    mobileMin: 23,
    mobileN: "4 sites",
    sessileMax: 27,
    sessileMin: 21,
    sessileN: "4 sites"
  },
  summer2021: {
    highShoreTemp: 51.2,
    highShoreTempDelta: 3.5,
    highShoreTempN: "4 sites",
    lowShoreTemp: 44.6,
    lowShoreTempDelta: 2.6,
    lowShoreTempN: "4 sites",
    chla: 12.7,
    chlaDelta: 6.67,
    chlaN: "4 sites",
    om: 7.91,
    omDelta: 3.14,
    omN: "4 sites",
    waveMax: 615.54,
    waveMin: 29.62,
    waveN: "4 sites",
    mobileMax: 59,
    mobileMin: 33,
    mobileN: "4 sites",
    sessileMax: 36,
    sessileMin: 25,
    sessileN: "4 sites"
  }
};

export default landingSO;
