const landingEA = {
  winter2020: {
    highShoreTemp: 38.0,
    highShoreTempDelta: 4.8,
    highShoreTempN: "4 sites",
    lowShoreTemp: 33.0,
    lowShoreTempDelta: 8.5,
    lowShoreTempN: "4 sites",
    chla: 6.91,
    chlaDelta: 4.27,
    chlaN: "4 sites",
    om: 5.66,
    omDelta: 3.40,
    omN: "4 sites",
    waveMax: 402.34,
    waveMin: 4.51,
    waveN: "4 sites",
    mobileMax: 24,
    mobileMin: 24,
    mobileN: "1 site",
    sessileMax: 15,
    sessileMin: 15,
    sessileN: "1 site"
  },
  summer2021: {
    highShoreTemp: 54.0,
    highShoreTempDelta: "NA",
    highShoreTempN: "1 site",
    lowShoreTemp: 53.3,
    lowShoreTempDelta: "NA",
    lowShoreTempN: "1 site",
    chla: "NA",
    chlaDelta: "NA",
    chlaN: "NA",
    om: "NA",
    omDelta: "NA",
    omN: "NA",
    waveMax: 402.34,
    waveMin: 4.51,
    waveN: "4 sites",
    mobileMax: "NA",
    mobileMin: "NA",
    mobileN: "NA",
    sessileMax: "NA",
    sessileMin: "NA",
    sessileN: "NA"
  }
};

export default landingEA;
