const landingTL = {
  winter2020: {
    highShoreTemp: 44.2,
    highShoreTempDelta: 3.4,
    highShoreTempN: "4 sites",
    lowShoreTemp: 37.0,
    lowShoreTempDelta: 2.2,
    lowShoreTempN: "4 sites",
    chla: 11.66,
    chlaDelta: 10.33,
    chlaN: "4 sites",
    om: 14.43,
    omDelta: 8.41,
    omN: "4 sites",
    waveMax: 56.16,
    waveMin: 21.29,
    waveN: "4 sites",
    mobileMax: 25,
    mobileMin: 17,
    mobileN: "4 sites",
    sessileMax: 24,
    sessileMin: 14,
    sessileN: "4 sites"
  },
  summer2021: {
    highShoreTemp: 53.6,
    highShoreTempDelta: 1.4,
    highShoreTempN: "4 sites",
    lowShoreTemp: 50.4,
    lowShoreTempDelta: 2.2,
    lowShoreTempN: "4 sites",
    chla: 12.4,
    chlaDelta: 6.01,
    chlaN: "4 sites",
    om: 15.74,
    omDelta: 9.35,
    omN: "4 sites",
    waveMax: 56.16,
    waveMin: 21.29,
    waveN: "4 sites",
    mobileMax: 39,
    mobileMin: 28,
    mobileN: "4 sites",
    sessileMax: 42,
    sessileMin: 18,
    sessileN: "4 sites"
  }
};

export default landingTL;
