const landingNE = {
  winter2020: {
    highShoreTemp: 42.1,
    highShoreTempDelta: 4.4,
    highShoreTempN: "4 sites",
    lowShoreTemp: 37.0,
    lowShoreTempDelta: 5.1,
    lowShoreTempN: "4 sites",
    chla: 9.41,
    chlaDelta: 0.78,
    chlaN: "4 sites",
    om: 8.44,
    omDelta: 1.37,
    omN: "4 sites",
    waveMax: 82.21,
    waveMin: 23.30,
    waveN: "4 sites",
    mobileMax: 39,
    mobileMin: 26,
    mobileN: "4 sites",
    sessileMax: 29,
    sessileMin: 16,
    sessileN: "4 sites"
  },
  summer2021: {
    highShoreTemp: 53.2,
    highShoreTempDelta: 2.2,
    highShoreTempN: "4 sites",
    lowShoreTemp: 49.9,
    lowShoreTempDelta: 3.0,
    lowShoreTempN: "4 sites",
    chla: 11.18,
    chlaDelta: 4.33,
    chlaN: "4 sites",
    om: 9.75,
    omDelta: 2.66,
    omN: "4 sites",
    waveMax: 82.21,
    waveMin: 23.30,
    waveN: "4 sites",
    mobileMax: 63,
    mobileMin: 31,
    mobileN: "4 sites",
    sessileMax: 44,
    sessileMin: 25,
    sessileN: "4 sites"
  }
};

export default landingNE;
