const landingTL = {
  winter2020: {
    highShoreTemp: 44.2,
    highShoreTempDelta: 3.4,
    highShoreTempN: "4 sites",
    lowShoreTemp: 37.0,
    lowShoreTempDelta: 2.2,
    lowShoreTempN: "4 sites",
    chla: 11.66,
    chlaDelta: 10.33,
    chlaN: "4 sites",
    om: 14.43,
    omDelta: 8.41,
    omN: "4 sites",
    waveMax: 17.98,
    waveMin: 12.31,
    waveN: "4 sites",
    mobileMax: 22,
    mobileMin: 17,
    mobileN: "1 site",
    sessileMax: 15,
    sessileMin: 13,
    sessileN: "1 site"
  },
  summer2021: {
    highShoreTemp: 51.7,
    highShoreTempDelta: 2.4,
    highShoreTempN: "4 sites",
    lowShoreTemp: 45.9,
    lowShoreTempDelta: 2.6,
    lowShoreTempN: "4 sites",
    chla: 12.4,
    chlaDelta: 6.01,
    chlaN: "4 sites",
    om: 15.74,
    omDelta: 9.35,
    omN: "4 sites",
    waveMax: 17.98,
    waveMin: 12.31,
    waveN: "4 sites",
    mobileMax: "NA",
    mobileMin: "NA",
    mobileN: "NA",
    sessileMax: "NA",
    sessileMin: "NA",
    sessileN: "NA"
  }
};

export default landingTL;
